# Generated by Django 6.0.2 on 2026-07-30 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmerapp', '0010_add_translation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_uuid', models.CharField(max_length=100, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irriwatch_order_uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='satelliteapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irriwatch_field_uuid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CREATED', 'Created'), ('SYNCING', 'Syncing'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_farms', to='farmerapp.farm')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_farms', to='satelliteapp.order')),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteFarmAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('CRITICAL_WATER_STRESS', 'Critical Water Stress'), ('OVERWATERING_DETECTED', 'Overwatering Detected'), ('CROP_HEALTH_DROPPING', 'Crop Health Dropping'), ('RAIN_ALERT_SKIP_IRRIGATION', 'Rain Alert Skip Irrigation')], max_length=100)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('observation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_alerts', to='satelliteapp.orderfarm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order_farm', 'observation_date', 'alert_type'), name='uniq_satellite_alert_per_field_date_type')],
            },
        ),
        migrations.CreateModel(
            name='SatelliteFarmNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('YOUR_FIELD_IS_DRYING', 'Your Field Is Drying'), ('MOISTURE_IS_IDEAL', 'Moisture Is Ideal'), ('GROWTH_LOOKS_GREAT', 'Growth Looks Great'), ('MONITOR_FIELD_CLOSELY_CROP_HEALTH', 'Monitor Field Closely Crop Health'), ('MONITOR_FIELD_CLOSELY_FERTILIZER_LEVELS', 'Monitor Field Closely Fertilizer Levels'), ('PLAN_IRRIGATION_THIS_WEEK', 'Plan Irrigation This Week')], max_length=100)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('observation_date', models.DateField()),
                ('is_read', models.BooleanField(default=False)),
                ('push_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('NO_DEVICES', 'No Devices')], db_index=True, default='PENDING', max_length=20)),
                ('push_failure_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_notifications', to='satelliteapp.orderfarm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order_farm', 'observation_date', 'notification_type'), name='uniq_satellite_notification_per_field_date_type')],
            },
        ),
        migrations.CreateModel(
            name='SatelliteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('tiff_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='satelliteapp.orderfarm')),
            ],
            options={
                'indexes': [models.Index(fields=['order_farm', 'observation_date'], name='satelliteap_order_f_40f29d_idx')],
            },
        ),
    ]
