# Generated by Django 6.0.2 on 2026-04-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteEventReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField(unique=True)),
                ('batch_id', models.CharField(blank=True, default='', max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('external_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('order_field_id', models.BigIntegerField(db_index=True)),
                ('observation_date', models.DateField(db_index=True)),
                ('generated_at', models.DateTimeField()),
                ('payload_json', models.JSONField()),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='RECEIVED', max_length=20)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
