# Generated by Django 6.0.2 on 2026-04-26 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0008_add_crop_variety_and_custom_names'),
        ('satelliteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteFarmAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_index', models.PositiveIntegerField()),
                ('alert_type', models.CharField(max_length=100)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('event_created_at', models.DateTimeField(blank=True, null=True)),
                ('observation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_alerts', to='farmerapp.farm')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rows', to='satelliteapp.satelliteeventreceipt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('receipt', 'source_index'), name='uniq_satellite_alert_per_receipt_index')],
            },
        ),
        migrations.CreateModel(
            name='SatelliteFarmNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_index', models.PositiveIntegerField()),
                ('notification_type', models.CharField(max_length=100)),
                ('details_json', models.JSONField(blank=True, default=dict)),
                ('event_created_at', models.DateTimeField(blank=True, null=True)),
                ('observation_date', models.DateField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_notifications', to='farmerapp.farm')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rows', to='satelliteapp.satelliteeventreceipt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('receipt', 'source_index'), name='uniq_satellite_notification_per_receipt_index')],
            },
        ),
    ]
