# Generated by Django 6.0.2 on 2026-07-31 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satelliteapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteMapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField()),
                ('band_number', models.PositiveSmallIntegerField()),
                ('layer_name', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('png_url', models.TextField()),
                ('bounds', models.JSONField(default=dict)),
                ('legend', models.JSONField(default=list)),
                ('is_categorical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_layers', to='satelliteapp.orderfarm')),
            ],
            options={
                'indexes': [models.Index(fields=['order_farm', 'observation_date'], name='satelliteap_order_f_30f5f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('order_farm', 'observation_date', 'band_number'), name='uniq_map_layer_per_field_date_band')],
            },
        ),
    ]
