# Generated by Django 6.0.2 on 2026-03-18 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=150)),
                ('taluka', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('fpo', 'FPO'), ('farmer', 'Farmer')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FpoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpo_name', models.CharField(max_length=255)),
                ('contact_person_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('gst_number', models.CharField(max_length=50)),
                ('pan_number', models.CharField(max_length=50)),
                ('cin_number', models.CharField(max_length=50)),
                ('pan_file', models.FileField(blank=True, null=True, upload_to='documents/fpo/pan/')),
                ('cin_file', models.FileField(blank=True, null=True, upload_to='documents/fpo/cin/')),
                ('gst_file', models.FileField(blank=True, null=True, upload_to='documents/fpo/gst/')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fpo_profiles', to='authapp.address')),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fpo_profile', to='authapp.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('aadhaar_number', models.CharField(max_length=50)),
                ('aadhaar_file', models.FileField(blank=True, null=True, upload_to='documents/farmer/aadhaar/')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_profiles', to='authapp.address')),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to='authapp.appuser')),
                ('registered_with_fpo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_farmers', to='authapp.fpoprofile')),
            ],
        ),
    ]
