# Generated by Django 6.0.2 on 2026-03-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Locality',
        ),
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='address',
            new_name='locality',
        ),
        migrations.RenameField(
            model_name='fpoprofile',
            old_name='address',
            new_name='locality',
        ),
    ]
