# Generated by Django 6.0.2 on 2026-03-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_rename_address_locality_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('pin_code', 'village', 'taluka', 'district', 'state'), name='unique_locality_combination'),
        ),
    ]
