# Generated by Django 6.0.2 on 2026-03-24 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_locality_unique_locality_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='PIN code must contain exactly 6 digits.', regex='^\\d{6}$')]),
        ),
    ]
