# Generated by Django 6.0.2 on 2026-03-31 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_alter_locality_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='email',
        ),
    ]
