# Generated by Django 6.0.2 on 2026-04-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_standardize_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('FPO', 'FPO'), ('FARMER', 'FARMER')], max_length=20),
        ),
    ]
