# Generated by Django 6.0.2 on 2026-05-08 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_appuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('FPO', 'FPO'), ('FARMER', 'FARMER'), ('ORG_USER', 'Org User')], max_length=20),
        ),
        migrations.CreateModel(
            name='HierarchyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(help_text='1 = highest in hierarchy; larger numbers = lower levels.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hierarchy_levels', to='authapp.organization')),
            ],
            options={
                'ordering': ['organization', 'level'],
                'unique_together': {('organization', 'level'), ('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('path', models.CharField(blank=True, default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hierarchy_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_units', to='authapp.hierarchylevel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_units', to='authapp.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='authapp.orgunit')),
            ],
            options={
                'ordering': ['organization', 'path'],
            },
        ),
        migrations.CreateModel(
            name='OrgMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_membership', to='authapp.appuser')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='authapp.orgunit')),
            ],
            options={
                'ordering': ['org_unit'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnitFPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpo_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='org_unit_link', to='authapp.fpoprofile')),
                ('org_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fpo_links', to='authapp.orgunit')),
            ],
            options={
                'ordering': ['org_unit'],
            },
        ),
    ]
