# Generated by Django 6.0.2 on 2026-05-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_hierarchy_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ORG_USER', 'Org User'), ('FPO', 'FPO'), ('FARMER', 'FARMER')], max_length=20),
        ),
    ]
