# Generated by Django 6.0.2 on 2026-07-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_add_super_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('gu', 'Gujarati'), ('pa', 'Punjabi'), ('bn', 'Bangla'), ('kn', 'Kannada'), ('te', 'Telugu'), ('ta', 'Tamil')], default='en', max_length=5),
        ),
    ]
