# Generated by Django 6.0.2 on 2026-04-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatellitePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('duration_days', models.PositiveIntegerField(unique=True)),
                ('duration_months', models.PositiveIntegerField()),
                ('base_price_per_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('total_price_per_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount_per_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_gst_per_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_commission_per_acre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['duration_days'],
            },
        ),
    ]
