
"""Stable, machine-readable response codes.

The frontend maps these codes to localized UI copy. ``message`` on the API
envelope stays English (developer-facing / fallback); the ``code`` is the
contract. Codes must be stable — never rename one to match reworded English
text, or every frontend mapping breaks. This module is the single source of
truth; keep it in sync with the mobile app's code table.
"""


class ResponseCode:
    # --- Generic ---
    SUCCESS = "SUCCESS"
    ERROR = "ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"

    # --- Generic CRUD success (used by FormattedResponseMixin defaults) ---
    DATA_FETCHED = "DATA_FETCHED"
    CREATED = "CREATED"
    UPDATED = "UPDATED"
    DELETED = "DELETED"

    # --- Role / auth ---
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    TOKEN_REFRESHED = "TOKEN_REFRESHED"
    AUTH_ERROR = "AUTH_ERROR"
    OTP_ELIGIBLE = "OTP_ELIGIBLE"
    FARMER_NOT_FOUND_FOR_PHONE = "FARMER_NOT_FOUND_FOR_PHONE"
    APP_USER_NOT_FOUND = "APP_USER_NOT_FOUND"
    FARMER_ONLY = "FARMER_ONLY"
    FPO_ONLY = "FPO_ONLY"
    FARMER_OR_FPO_ONLY = "FARMER_OR_FPO_ONLY"
    NO_APPUSER_PROFILE = "NO_APPUSER_PROFILE"
    INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN"
    IMPERSONATION_TOKEN_ISSUED = "IMPERSONATION_TOKEN_ISSUED"
    TARGET_USER_NOT_FOUND = "TARGET_USER_NOT_FOUND"
    ACCOUNT_CREATED = "ACCOUNT_CREATED"

    # --- Input / format validation ---
    OBSERVATION_DATE_REQUIRED = "OBSERVATION_DATE_REQUIRED"
    OBSERVATION_DATE_INVALID = "OBSERVATION_DATE_INVALID"
    PHONE_FORMAT_INVALID = "PHONE_FORMAT_INVALID"
    PIN_FORMAT_INVALID = "PIN_FORMAT_INVALID"
    INVALID_DATA = "INVALID_DATA"

    # --- Preferences ---
    LANGUAGE_UPDATED = "LANGUAGE_UPDATED"

    # --- Farmer ---
    FARMER_PROFILE_FETCHED = "FARMER_PROFILE_FETCHED"
    FARMER_PROFILE_UPDATED = "FARMER_PROFILE_UPDATED"
    FARMER_PROFILE_NOT_FOUND = "FARMER_PROFILE_NOT_FOUND"
    FARMER_DETAILS_FETCHED = "FARMER_DETAILS_FETCHED"
    FARMER_NOT_FOUND = "FARMER_NOT_FOUND"
    FARMER_NOT_IN_FPO = "FARMER_NOT_IN_FPO"
    FARMER_CREATED = "FARMER_CREATED"
    FARMERS_FOUND = "FARMERS_FOUND"
    FARMS_FOR_FARMER = "FARMS_FOR_FARMER"
    FARMERS_IN_DISTRICT = "FARMERS_IN_DISTRICT"
    DISTRICTS_IN_STATE = "DISTRICTS_IN_STATE"
    FILTER_STATES = "FILTER_STATES"

    # --- FPO ---
    FPO_PROFILE_FETCHED = "FPO_PROFILE_FETCHED"
    FPO_PROFILE_UPDATED = "FPO_PROFILE_UPDATED"
    FPO_PROFILE_NOT_FOUND = "FPO_PROFILE_NOT_FOUND"
    FPO_DETAILS_FETCHED = "FPO_DETAILS_FETCHED"
    FPO_NOT_FOUND = "FPO_NOT_FOUND"
    FPO_LIST_FETCHED = "FPO_LIST_FETCHED"
    FPO_STATS = "FPO_STATS"
    FPO_OVERVIEW_FETCHED = "FPO_OVERVIEW_FETCHED"
    FPOS_FOUND = "FPOS_FOUND"
    FPO_FARMERS_FETCHED = "FPO_FARMERS_FETCHED"
    FPO_FARMER_CONTACTS_FETCHED = "FPO_FARMER_CONTACTS_FETCHED"

    # --- Satellite ---
    SATELLITE_NOT_SUBSCRIBED = "SATELLITE_NOT_SUBSCRIBED"
    SATELLITE_DATA_PENDING = "SATELLITE_DATA_PENDING"
    SATELLITE_NOT_ENABLED = "SATELLITE_NOT_ENABLED"
    SATELLITE_AWAITING_DATA = "SATELLITE_AWAITING_DATA"
    SATELLITE_DATE_UNAVAILABLE = "SATELLITE_DATE_UNAVAILABLE"
    SATELLITE_ERROR = "SATELLITE_ERROR"
    SATELLITE_DATA_FETCHED = "SATELLITE_DATA_FETCHED"
    SATELLITE_OVERVIEW_FETCHED = "SATELLITE_OVERVIEW_FETCHED"
    SATELLITE_MAP_LAYERS_FETCHED = "SATELLITE_MAP_LAYERS_FETCHED"
    SATELLITE_INSIGHTS_FETCHED = "SATELLITE_INSIGHTS_FETCHED"
    SATELLITE_INSIGHTS_NOT_FOUND = "SATELLITE_INSIGHTS_NOT_FOUND"
    SATELLITE_CHARTS_FETCHED = "SATELLITE_CHARTS_FETCHED"
    SATELLITE_CHARTS_NOT_FOUND = "SATELLITE_CHARTS_NOT_FOUND"
    SATELLITE_EVENTS_FETCHED = "SATELLITE_EVENTS_FETCHED"

    # --- Billing / pricing ---
    PRICING_FETCHED = "PRICING_FETCHED"
    NO_ACTIVE_PLANS = "NO_ACTIVE_PLANS"
    SINGLE_FARM_PRICING = "SINGLE_FARM_PRICING"
    INVALID_FARM_IDS = "INVALID_FARM_IDS"
    SUBSCRIPTION_SUMMARY = "SUBSCRIPTION_SUMMARY"
    PER_FPO_SUBSCRIPTION = "PER_FPO_SUBSCRIPTION"

    # --- Admin / hierarchy ---
    ORG_UNIT_NOT_FOUND = "ORG_UNIT_NOT_FOUND"
    SUBTREE_RETRIEVED = "SUBTREE_RETRIEVED"
    PLATFORM_STATS = "PLATFORM_STATS"

    # --- Billing / plans ---
    ACTIVE_PLANS = "ACTIVE_PLANS"

    # --- Notifications ---
    NO_DEVICE_TOKEN = "NO_DEVICE_TOKEN"
    DEVICE_TOKEN_STATS = "DEVICE_TOKEN_STATS"
    DEVICE_TOKEN_REGISTERED = "DEVICE_TOKEN_REGISTERED"
    DEVICE_TOKEN_NOT_FOUND = "DEVICE_TOKEN_NOT_FOUND"
    DEVICE_TOKEN_UNREGISTERED = "DEVICE_TOKEN_UNREGISTERED"
