# Generated by Django 6.0.2 on 2026-04-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
