# Generated by Django 6.0.2 on 2026-04-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0002_farm_farm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='area',
            field=models.FloatField(default=0, help_text='Area in acres, calculated from boundary polygon.'),
        ),
    ]
