# Generated by Django 6.0.2 on 2026-04-09 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0003_farm_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmSatelliteSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irriwatch_order_uuid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('irriwatch_field_uuid', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('subscription_start', models.DateField()),
                ('subscription_duration_months', models.PositiveIntegerField()),
                ('subscription_end', models.DateField()),
                ('payment_reference', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('SUBMITTED', 'Submitted'), ('SYNCING', 'Syncing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PAID', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_subscriptions', to='farmerapp.farm')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('subscription_end__gte', models.F('subscription_start'))), name='satellite_subscription_end_after_start'), models.UniqueConstraint(condition=models.Q(('status__in', ['PAID', 'SUBMITTED', 'SYNCING'])), fields=('farm',), name='unique_active_subscription_per_farm')],
            },
        ),
    ]
