# Generated by Django 6.0.2 on 2026-04-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0004_farmsatellitesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcrop',
            name='cropping_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('INTERCROP', 'Intercrop')], default='PRIMARY', max_length=10),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='primary_crop',
            field=models.ForeignKey(blank=True, help_text='For intercrops, the primary crop this is planted alongside.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intercrops', to='farmerapp.farmcrop'),
        ),
    ]
