# Generated by Django 6.0.2 on 2026-04-15 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0005_add_intercropping_support'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmcrop',
            name='cropping_type',
        ),
        migrations.RemoveField(
            model_name='farmcrop',
            name='primary_crop',
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='intercrop',
            field=models.ForeignKey(blank=True, help_text='Optional second crop grown alongside the primary crop (intercropping).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercrop_farm_crops', to='farmerapp.croptype'),
        ),
    ]
