# Generated by Django 6.0.2 on 2026-04-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0006_collapse_intercrop_single_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmcrop',
            old_name='crop_type',
            new_name='primary_crop',
        ),
    ]
