# Generated by Django 6.0.2 on 2026-04-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0007_rename_crop_type_to_primary_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcrop',
            name='custom_intercrop_name',
            field=models.CharField(blank=True, default='', help_text='Custom intercrop name when not in the CropType list.', max_length=100),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='custom_primary_crop_name',
            field=models.CharField(blank=True, default='', help_text='Custom crop name when not in the CropType list.', max_length=100),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='intercrop_variety',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='primary_crop_variety',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmcrop',
            name='primary_crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_crops', to='farmerapp.croptype'),
        ),
    ]
