# Generated by Django 6.0.2 on 2026-05-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0008_add_crop_variety_and_custom_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmsatellitesubscription',
            name='irriwatch_order_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmsatellitesubscription',
            name='subscription_end',
            field=models.DateField(editable=False),
        ),
    ]
