# Generated by Django 6.0.2 on 2026-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='platform',
            field=models.CharField(choices=[('ios', 'Ios'), ('android', 'Android')], max_length=10),
        ),
    ]
